# Generated by Django 5.0 on 2023-12-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_posts_date_post_alter_user_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
